[env:weact_stm32h562]
platform = ststm32
board = nucleo_h563zi
board_build.mcu = stm32h562vit6
board_build.f_cpu = 250000000L
build_flags =
  -O3
  -mfloat-abi=hard
  -mfpu=fpv5-sp-d16
  -I ../../src
build_src_filter = +<*>
build_unflags = -mfloat-abi=soft -mfloat-abi=softfp
extra_scripts = pre:linker_flags.py
