#pragma once

#define DIMENSION_TARGET_STM32H562 1

#define DIMENSION_SAMPLE_RATE_DEFAULT 48000.0f
#define DIMENSION_MAX_BLOCK_SIZE 64

#define DIMENSION_DELAY_SIZE 2048
#define DIMENSION_DELAY_MASK (DIMENSION_DELAY_SIZE - 1)

#define DIMENSION_USE_FLOAT32 1
#define DIMENSION_USE_CMSIS_DSP 0

#define DIMENSION_ENABLE_NOISE 0
#define DIMENSION_ENABLE_CLOCK_BLEED 0
#define DIMENSION_ENABLE_SAFETY_LIMITER 1

#define DIMENSION_INTERP_LINEAR 0
#define DIMENSION_INTERP_HERMITE 1
#define DIMENSION_INTERP_LAGRANGE3 2

#define DIMENSION_INTERP_MODE DIMENSION_INTERP_HERMITE

#if defined(__GNUC__)
#define DIMENSION_ALIGN_32 __attribute__((aligned(32)))
#else
#define DIMENSION_ALIGN_32
#endif
